version: "3"
services:
  gm:
    build: .
    # image: ghcr.io/rollkit/gm:19b894c
    # Also for targetting localhost as if you were outside the container
    network_mode: host
    # Use for bringing up docker image and keeping open
    # command: tail -F anything
    # command: rollkit start --rollkit.aggregator --rollkit.da_address http://localhost:7980
    depends_on:
      - local-da

  local-da:
    image: ghcr.io/rollkit/local-da:aa37274
    ports:
      - "7980:7980"
