version: "3"

services:
  celestia:
    image: ghcr.io/rollkit/local-celestia-devnet:v0.9.0
    restart: unless-stopped
    expose:
      - "26657"
      - "26659"
    # Rollup can't start until after DA starts.
    # This ensures it waits 5 seconds so the rollup can query it.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/block?height=1"]
      interval: 5s
      timeout: 10s
      retries: 5
  gm:
    build:
      context: .
    restart: unless-stopped
    expose:
      - "26656"
    ports:
      - "26657:26657"
    environment:
      - RPC=http://celestia:26657/
      - START_ARGS=--rollkit.aggregator
    depends_on:
      celestia:
        condition: service_healthy
