version: "3"

services:
  celestia-light-node:
    image: ghcr.io/celestiaorg/celestia-node:v0.8.2
    expose:
      - "26659"
    ports:
      - "26659:26659"
    environment:
      - NODE_TYPE=light
      - P2P_NETWORK=blockspacerace-0
    command: celestia light start --core.ip https://rpc-blockspacerace.pops.one/ --gateway --gateway.addr 0.0.0.0 --gateway.port 26659 --p2p.network blockspacerace-0
  gm:
    build:
      context: .
    expose:
      - "26656"
    ports:
      - "26657:26657"
    depends_on:
      celestia-light-node:
        condition: service_started

