name: Test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  gm-docker-compose:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using docker-compose-action
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "compose.yaml"
          up-flags: "--build"
          test-container: gm
          # Run the GM tutorial and halt after 10 blocks
          test-command: "rollkit start --rollkit.aggregator --rollkit.da_address http://localhost:7980 --halt-height 10"
